project:
  type: website
  output-dir: docs

website:
  title: "<b>CAUSAL DATA SCIENCE FOR BUSINESS ANALYTICS</b>"
  page-navigation: true
  favicon: images/favicon_cds_16x16.png
  navbar:
    background: "#323e4dE6"
    pinned: false
    logo: images/icon_cds_text.png
    right:
      - href: index.qmd
        text: Home
      - text: Content
        file: content/index.qmd
      - text: Submission
        file: submission/submission.qmd
      - text: "{{< iconify cib mattermost size=lg >}}"
        href: https://communicating.tuhh.de/w-11-students/channels/discussion-causal-data-science

  sidebar:
    - title: "Contents"
      style: "docked"
      background: "#112030"
      contents:
        - text: "<b>Introduction</b>"
          file: content/index.qmd
        - text: "---"
        - section: "<b>Fundamentals</b>"
          contents:
            - content/fundamentals/01_a_prob.qmd
            - content/fundamentals/01_b_stats.qmd
            - content/fundamentals/02_reg.qmd
            - content/fundamentals/03_caus.qmd
            - content/fundamentals/04_dag.qmd
        - text: "---"
        - section: "<b>Toolbox</b>"
          contents:
            - content/toolbox/05_rct.qmd
            - content/toolbox/06_match.qmd
            - content/toolbox/07_did.qmd
            - content/toolbox/08_iv.qmd
            - content/toolbox/09_rdd.qmd
    - title: "Home"

  page-footer: 
    left: "lv3060 WiSe 23/24: Causal Data Science for Business Analytics" 

format:
  html:
    theme: [darkly, theme-darkly.scss]
    mainfont: arial
    linestretch: 1.7
    css: styles.css
    toc: true
    df-print: paged
    code-link: true

filters:
 - lightbox
lightbox:
  match: auto

editor: visual

