project:
  type: website
  output-dir: docs

website:
  title: "<b>CAUSAL DATA SCIENCE FOR BUSINESS ANALYTICS</b>"
  page-navigation: true
  favicon: images/favicon_cds_16x16.png
  navbar:
    background: "#005E73"
    pinned: true
    logo: images/icon_cds_text.png
    right:
      - href: index.qmd
        text: Home
      - text: Content
        file: content/index.qmd
      - icon: chat-left-text-fill
        href: https://communicating.tuhh.de/w-11-students/channels/test_intro
        aria-label: Mattermost
  
  sidebar:
    - title: "Contents"
      style: "docked"
      background: "#011627"
      contents:
        - text: "Overview"
          file: content/index.qmd
        - section: "Fundamentals"
          contents:
            - content/fundamentals/01_prob.qmd
            - content/fundamentals/02_reg.qmd
            - content/fundamentals/03_caus.qmd
            - content/fundamentals/04_dag.qmd
        - section: "Toolbox"
          contents:
            - content/toolbox/05_rct.qmd
            - content/toolbox/06_match.qmd
            - content/toolbox/07_did.qmd
            - content/toolbox/08_iv.qmd
            - content/toolbox/09_rdd.qmd
    - title: "Home"

  page-footer: 
    left: "Winter term 2022/2023 - Causal Data Science for Business Analytics" 

format:
  html:
    theme: [darkly, theme-darkly.scss]
    mainfont: arial
    linestretch: 1.7
    css: styles.css
    toc: true
    df-print: paged

editor: visual

